--setup.sql

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_RALLY
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE WH_RALLY;

-- Database + Schema
CREATE DATABASE IF NOT EXISTS BOOTCAMP_RALLY;
USE DATABASE BOOTCAMP_RALLY;

CREATE SCHEMA IF NOT EXISTS RALLY;
USE SCHEMA RALLY;

-- RACE_EVENTS (one row per race event)
CREATE OR REPLACE TABLE BOOTCAMP_RALLY.RALLY.RACE_EVENTS (
    RACE_ID INT AUTOINCREMENT PRIMARY KEY,
    DISTANCE FLOAT NOT NULL,
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TEAMS (only name + budget)
CREATE OR REPLACE TABLE BOOTCAMP_RALLY.RALLY.TEAMS (
    TEAM_ID INT AUTOINCREMENT PRIMARY KEY,
    TEAM_NAME STRING NOT NULL UNIQUE,
    BUDGET NUMBER(12,2) NOT NULL
);

-- CARS (linked to teams)
CREATE OR REPLACE TABLE BOOTCAMP_RALLY.RALLY.CARS (
    CAR_ID INT AUTOINCREMENT PRIMARY KEY,
    CAR_NAME STRING NOT NULL UNIQUE,
    SPEED FLOAT NOT NULL,
    PIT_STOP_INTERVAL FLOAT NOT NULL,
    PIT_STOP_DURATION FLOAT NOT NULL,
    TEAM_ID INT NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES BOOTCAMP_RALLY.RALLY.TEAMS(TEAM_ID) ON DELETE CASCADE
);

-- RACE_ENTRIES (cars participating in race)
CREATE OR REPLACE TABLE BOOTCAMP_RALLY.RALLY.RACE_ENTRIES (
    ENTRY_ID INT AUTOINCREMENT PRIMARY KEY,
    RACE_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    TIME_TAKEN FLOAT,
    FEE NUMBER(12,2),
    FOREIGN KEY (RACE_ID) REFERENCES BOOTCAMP_RALLY.RALLY.RACE_EVENTS(RACE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES BOOTCAMP_RALLY.RALLY.TEAMS(TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (CAR_ID) REFERENCES BOOTCAMP_RALLY.RALLY.CARS(CAR_ID) ON DELETE CASCADE
);

-- RACE_RESULTS (position + prize)
CREATE OR REPLACE TABLE BOOTCAMP_RALLY.RALLY.RACE_RESULTS (
    RESULT_ID INT AUTOINCREMENT PRIMARY KEY,
    RACE_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    POSITION INT,
    PRIZE_MONEY NUMBER(12,2) DEFAULT 0,
    FOREIGN KEY (RACE_ID) REFERENCES BOOTCAMP_RALLY.RALLY.RACE_EVENTS(RACE_ID) ON DELETE CASCADE
);

-- Sample Data
INSERT INTO BOOTCAMP_RALLY.RALLY.TEAMS (TEAM_NAME, BUDGET)
VALUES
    ('Speed Devils', 50000.00),
    ('Thunder Racing', 75000.00),
    ('Phoenix Motors', 60000.00);

INSERT INTO BOOTCAMP_RALLY.RALLY.CARS (CAR_NAME, SPEED, PIT_STOP_INTERVAL, PIT_STOP_DURATION, TEAM_ID)
VALUES
    ('Bolt X1', 180.5, 50.0, 15.5, 1),
    ('Thunder GT', 195.2, 45.0, 12.0, 2),
    ('Phoenix Fire', 188.7, 48.0, 13.8, 3);
